# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('delete_on_download', models.BooleanField(default=True)),
            ],
        ),
    ]
